name: Publish Docker image
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Copy repo files
        uses: actions/checkout@master

      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

      - name: Publish image to GitHub Package Registry
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          # docker pull ghcr.io/usernam3/usernam3/${{github.repository}}
          docker build . --tag ghcr.io/usernam3/${{github.repository}}:${{ env.RELEASE_VERSION }} --tag ghcr.io/usernam3/${{github.repository}}:latest --cache-from ghcr.io/usernam3/${{github.repository}}
          docker push ghcr.io/usernam3/${{github.repository}}:${{ env.RELEASE_VERSION }}
